### ISSUE TITLE
0.20.0下assembleRelease失败

### ISSUE THREAD

**Issue by vincentchen** [ReactLover/react-native-2048#6]
TransformError: /Users/vincent/Downloads/OpenSource/2048/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update                                                              /lib/index.js: [BABEL] /Users/vincent/Downloads/OpenSource/2048/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/lib/index.js: Unknown option: /Users/vincent/Downloads/OpenSource/2048/node_modules/react-native/node_modules/react-transform-hmr/node_modules/react-proxy/node_modules/react-deep-force-update/.babelrc.stage
See logs /var/folders/0x/9ty_pmz91mq73mhdhc0xqg_w0000gn/T/react-packager.log
    at SocketClient._handleMessage (SocketClient.js:144:23)
    at BunserBuf.<anonymous> (SocketClient.js:53:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/vincent/Downloads/OpenSource/2048/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/vincent/Downloads/OpenSource/2048/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

**Comment by liuhong1happy** [comment]
This not my project issue,please see: `react-native issue`
[#5393](https://github.com/facebook/react-native/issues/5393)
